import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = (path) => readFileSync(new URL("../" + path, import.meta.url), "utf8");
const pkg = JSON.parse(read("package.json"));
const store = read("src/v4/store.ts");
const home = read("src/pages/index/index.tsx");
const units = read("src/pages/units/index.tsx");
const record = read("src/pages/record-form/index.tsx");
const ledger = read("src/pages/records/index.tsx");
const manage = read("src/pages/data-backup/index.tsx");
const profile = read("src/pages/profile/index.tsx");
const about = read("src/pages/about-data/index.tsx");
const pondForm = read("src/pages/pond-form/index.tsx");

assert.equal(pkg.version, "0.4.0");
assert.match(store, /fishery-manager:state:v3/);
assert.match(store, /legacy-backup/);
assert.match(store, /migrateV2ToV4/);
assert.match(store, /bindCurrentWechatAccount/);
assert.match(store, /syncV4State/);
assert.match(store, /uploadRecordPhotos/);
assert.match(home, /现场值守/);
assert.match(home, /经营概览/);
assert.match(home, /体验示例/);
assert.match(home, /微信登录（可选）/);
assert.match(home, /创建养殖单元/);
assert.doesNotMatch(home, /真实记录前请先绑定微信账号/);
assert.doesNotMatch(home, /92\\.6|42\\.3|1\\.42/);
assert.match(units, /养殖单元/);
assert.match(units, /塘口|网箱|室内池/);
assert.match(units, /sea-cage-photo/);
assert.match(units, /outdoor-pond-photo/);
assert.match(units, /indoor-ras-tanks/);
assert.match(units, /other-eco-aquaculture/);
assert.match(pondForm, /sea-cage-photo/);
assert.match(pondForm, /outdoor-pond-photo/);
assert.match(pondForm, /indoor-ras-tanks/);
assert.match(pondForm, /other-eco-aquaculture/);
assert.match(record, /常用记录/);
assert.match(record, /巡塘异常/);
assert.match(record, /斤|公斤/);
assert.match(record, /专业参数（可选）/);
assert.doesNotMatch(record, /请先绑定微信账号/);
assert.match(ledger, /record-chips/);
assert.match(ledger, /records-date-head/);
assert.match(profile, /经营工具/);
assert.match(profile, /数据服务/);
assert.match(manage, /本地数据状态/);
assert.match(manage, /微信账号（可选）/);
assert.match(manage, /饲料与药品库存/);
assert.match(manage, /成员与权限/);
assert.match(manage, /任务与提醒/);
assert.match(manage, /城市级天气/);
assert.match(manage, /完整加密备份/);
assert.match(manage, /注销账号/);
assert.match(about, /v\{APP_VERSION\}/);
console.log("0.4 UI boundary checks passed");
